# Generated by Django 3.1.4 on 2021-01-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_chat_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
