# Generated by Django 3.1.4 on 2021-01-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20210101_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='udate',
            field=models.DateTimeField(auto_created=True, auto_now=True, null=True),
        ),
    ]
