# Generated by Django 3.2.7 on 2021-09-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_chat_udate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
