# Generated by Django 3.2.7 on 2021-10-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
