# Generated by Django 3.2.7 on 2021-10-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_chat_last_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
