# Generated by Django 3.2.7 on 2021-10-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_chat_chat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='original_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
