# Generated by Django 3.2.7 on 2021-10-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_chat_original_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='original_response',
        ),
        migrations.AddField(
            model_name='message',
            name='original_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
